baseurl: '/jekyll-serif-theme/'
permalink: pretty
title: 'Jekyll Serif'

colors:
  # light
  base_bg: "#ffffff"
  base_bg_2: "#f8fafc"
  base_bg_3: "#f1f5f9"
  base_text: "#202020"
  base_text_2: "#4b5563"
  primary_bg: "#3b8132"
  primary_bg_2: "#424ff8"
  primary_bg_3: "#702bf7"
  primary_text: "#fdfcf9"
  header_text: "#2b3af7"
  logo_text: "#2b3af7"

  # dark
  base_bg_dark: "#121212"
  base_bg_2_dark: "#1e1e1e"
  base_bg_3_dark: "#232323"
  base_text_dark: "#ffffff"
  base_text_2_dark: "#d7d7d7"
  primary_bg_dark: "#2b3af7"
  primary_bg_2_dark: "#424ff8"
  primary_bg_3_dark: "#702bf7"
  primary_text_dark: "#fdfcf9"
  logo_text_dark: "#ffffff"
  header_text_dark: "#ffffff"

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Alex Miller Coaching"
  meta_og_type: "website"
  meta_og_url: "https://jekyll-serif.netlify.app"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "This is a one-to-one coaching container designed to help high-performing professionals understand their energy and work with it intentionally to reduce burnout and move through life with greater ease and joy."
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
